# Generated by Django 3.0.2 on 2020-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=300)),
                ('address', models.TextField(max_length=500)),
                ('salary', models.CharField(max_length=50)),
                ('post_url', models.CharField(max_length=200)),
                ('resource_url', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='jobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(max_length=200)),
            ],
        ),
    ]
