# Generated by Django 3.0.2 on 2020-01-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=500)),
                ('Industry', models.CharField(max_length=100)),
                ('company_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='jobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300)),
                ('salary', models.CharField(max_length=50)),
                ('post_url', models.CharField(max_length=200)),
                ('resource_url', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
                ('company', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.CompanyInfo')),
                ('job_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='jobs.jobStatus')),
            ],
        ),
    ]
