# Generated by Django 3.0.2 on 2020-01-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=500)),
                ('Industry', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='jobs.jobStatus'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.CompanyInfo'),
        ),
    ]
