# Generated by Django 3.0.2 on 2020-01-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='company_url',
        ),
    ]
