# Generated by Django 3.0.2 on 2020-01-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_companyinfo_company_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfo',
            old_name='job_stage',
            new_name='job_status',
        ),
    ]
