# Generated by Django 3.0.2 on 2020-01-23 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200113_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
