# Generated by Django 3.0.2 on 2020-02-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobinfo_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfo',
            old_name='company',
            new_name='companies',
        ),
    ]
